### ISSUE TITLE
copresentation view for whitelisting image/file URLs

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/cihm-metadatabus#2]
As discussed last week, get a view ready to help Cantaloupe and the file server know which file paths are whitelisted for direct access.

**Comment by SaschaAdler** [comment]
We're managing this by Swift tempURLs and the eventual access platform image repository, which will obviate the need for only making some files in a filesystem available to the public.

I think we can close this issue but I'll let @RussellMcOrmond confirm.

**Comment by RussellMcOrmond** [comment]
Agreed.  Eventually we'll be using noids for Image API references, and will be doing the appropriate couch/etc lookups at that time.
